apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-rag-scripts
data:
  backend-app.py: |
{{ .Files.Get "files/backend-app.py" | indent 4 }}
  tool-service-app.py: |
{{ .Files.Get "files/tool-service-app.py" | indent 4 }}
  agent-workflow-app.py: |
{{ .Files.Get "files/agent-workflow-app.py" | indent 4 }}
