apiVersion: v1
kind: Service
metadata:
  name: tool-service
  labels:
    app: tool-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.toolService.port }}
      targetPort: {{ .Values.toolService.port }}
      protocol: TCP
      name: http
  selector:
    app: tool-service
